version: 2

jobs:
  tests:
    docker:
      - image: circleci/php:7.4-browsers

    steps:
      - checkout

      - run: sudo apt-get update

      - restore_cache:
          keys:
            - v1-dependencies-{{ checksum "composer.json" }}
            - v1-dependencies-

      - run: composer install

      - save_cache:
          key: v1-dependencies-{{ checksum "composer.json" }}
          paths:
            - ./vendor

      - run: ./vendor/bin/phpunit

workflows:
  version: 2
  run-tests:
    jobs:
      - tests